### ISSUE TITLE
-s:<db> does not work on windows

### ISSUE THREAD

**Issue by DeepHorizons** [h3rald/litestore#32]
The executable defaults to data.db no matter what the -s or --store value is
Is the same for both the x86 and x64 builds.
Version 1.0.1

**Comment by h3rald** [comment]
Yep -- I actually noticed it a while ago and already fixed the issue in master (see #30) but I didn't release a new version yet. I will now :)

**Comment by h3rald** [comment]
@DeepHorizons Done! Try v1.0.2, it should work as expected.
