### ISSUE TITLE
Great Job

### ISSUE THREAD

**Issue by skellock** [h3rald/litestore#49]
Man, what a gem of a project.

Thank you for open sourcing this.

:heart_eyes_cat:

**Comment by skellock** [comment]
Closing, since I don't want to be responsible for this:

![image](https://user-images.githubusercontent.com/68273/51915509-4aa0ad00-23a9-11e9-962d-4b97b48753ed.png)

**Comment by h3rald** [comment]
😄 WOW! Thanks, very appreciated! Glad you like it.
