### ISSUE TITLE
Problems building from source

### ISSUE THREAD

**Issue by richboss** [h3rald/litestore#54]
Litestore seems to be a very interesting project, well done, congratulations! As I am interested in learning the Nim language I wanted to compile from source. Fortunately this looks easy enough. On a Windows 10 box I already had Nim 1.4.0 installed and working. After cloning the litestore repo, the next step is just `Run nim c litestore.nim within the respository folder`. But running this command in the root folder of the git clone doesn't work. The command has to be issued in the `src` subfolder. Hence the instructions should be reworded along the lines of `Run "nim c litestore.nim" within the "src" subfolder of the cloned repository.`

Next problem is that the `jwt` dependency is missing and has to be installed prior to compilation.

```
C:\litestore\src>nim c litestore.nim
Hint: used config file 'o:\app\nim\config\nim.cfg' [Conf]
Hint: used config file 'o:\app\nim\config\config.nims' [Conf]
Hint: used config file 'C:\litestore\src\litestore.nim.cfg' [Conf]
..................................................
C:\litestore\src\litestorepkg\lib\types.nim(12, 3) Error: cannot open file: jwt
```

This can easily be fixed with `nimble install jwt`. I don't know if it is possible to automatically download and install dependencies if they are missing. If not, it might be a good idea to mention this as a precondition in the instructions.

Lastly, the source code doesn't compile cleanly. I tried it on three different computers and it is always the same line that makes it fail:
```
c:\litestore\src>nim c litestore.nim
Hint: used config file 'o:\app\nim\config\nim.cfg' [Conf]
Hint: used config file 'o:\app\nim\config\config.nims' [Conf]
Hint: used config file 'c:\litestore\src\litestore.nim.cfg' [Conf]
..............................................................................
c:\litestore\src\litestorepkg\lib\server.nim(127, 13) template/generic instantiation of `auth` from here
c:\litestore\src\litestorepkg\lib\server.nim(66, 30) Error: type mismatch: got <string, seq[byte], string>
but expected one of:
proc verifySignature(data: string; signature: seq[byte]; secret: string;
                     alg: SignatureAlgorithm): bool
  first type mismatch at position: 4
  missing parameter: alg

expression: verifySignature(parts`gensym7[0] & "." & parts`gensym7[1],
                decodeUrlSafe(parts`gensym7[2]), sig`gensym7)
```
The problem is the invocation of the procedure `verifySignature` in line 66 of `server.nim`. Apparently the parameter count doesn't match. The proc invocation in `server.nim` has three args, but the jwt implementation expects four args. What is going on here? My jwt package is v0.2 - is that wrong? This is just what nimble installed.

The problematic code line doesn't seem absolutely necessary for basic functioning of Litestore. So I just commented it out. After that everything compiled and seemed to work just fine.

**Comment by h3rald** [comment]
Fixed compilation problems and removed that paragraph about building from source. As a matter of fact the best way to build and install LiteStore is just by running **nimble install litestore**.

Thanks!
