### ISSUE TITLE
Edit Content - nothing is shown

### ISSUE THREAD

**Issue by PlkMarudny** [h3rald/litestore#57]
Looks like 'Edit Content' does not really allows editing of a document, this is what is displayed on Chrome and Firefox:
![image](https://user-images.githubusercontent.com/4361591/100540561-7ae05d80-3257-11eb-8826-093e86658b8e.png)

This is for a document I created, API returns the proper content. I created the document using a GUI, pasting the content JSON into the ACE editor.

**Comment by h3rald** [comment]
Gotta rewrite the app... it's using a really old version of Mithril. But I'll take a look and see if I can fix this regression first, thanks!

**Comment by PlkMarudny** [comment]
BTW initial documents can be edited. Anyway, this project is amazing.

Tomasz Plonka

**Comment by h3rald** [comment]
Did some preliminary tests: looks like it's a problem with JSON files! If you try to create and edit a text/plain file it works fine. Will investigate...
