### ISSUE TITLE
CTRL-C crashes!

### ISSUE THREAD

**Issue by tonypdmtr** [h3rald/litestore#61]
Just press CTRL-C after having started litestore on the command line.  The app crashes - 100% repeatable.

**Comment by h3rald** [comment]
Alright alright... two things:

* CTRL+C is supposed to *gracefully* stop the LiteStore server. That's how you are supposed to stop it.
* On Windows, for some weird reason I never discovered, you also get a *Segmentation Fault* message, before the application closes.

...is that what you are observing? Are you on Windows?

**Comment by tonypdmtr** [comment]
Yes, that's what I observe on Windows 7 (various versions).

**Comment by h3rald** [comment]
This is no longer happening when compiling with the most recent version of Nim, closing.
