### ISSUE TITLE
download links in docs broken

### ISSUE THREAD

**Issue by maphew** [h3rald/litestore#68]
The links for the precompiled binaries in the docs are 404:

https://h3rald.com/litestore/LiteStore_UserGuide.htm#Downloading-Pre-built-Binaries
https://github.com/h3rald/litestore/blob/master/src/admin/md/getting-started.md

Downloading from Releases pages is okay:
https://github.com/h3rald/litestore/releases/

**Comment by h3rald** [comment]
Well spotted! Fixed, thanks!

**Comment by ITwrx** [comment]
https://github.com/h3rald/litestore/releases/download/1.11.0/litestore_1.11.0_linux_x64.zip
