### ISSUE TITLE
[Question] Does it support bootstrap?

### ISSUE THREAD

**Issue by melovv** [h3rald/litestore#73]
Hello. 

I was wondering if litestore is able to serve a dashboard developed using bootstrap. For instance, any bootstrap admin page such as SB Admin. 

https://startbootstrap.com/theme/sb-admin-2

Thanks!!!

**Comment by h3rald** [comment]
Sure it does, or better, it doesn't really matter what you use LiteStore with... LiteStore deals with the backend storage, on the client you can use whatever framework or library you want!

(In the admin app I used Bootstrap as an example... that's very old code now, but it still works)
